FROM ubuntu:16.04

MAINTAINER Blockchain Labs, NZ (Alex Tikonoff, alex@blockchainlabs.nz)

RUN apt-get update && apt-get install -y curl git python build-essential netcat \
    && apt-get -y autoclean

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash    
RUN apt-get install nodejs

ENV DIR=/audit
ENV VOL=/audit

RUN mkdir $DIR
COPY . $DIR
WORKDIR $DIR

RUN npm install

EXPOSE 8545
EXPOSE 8555

ENTRYPOINT ["npm", "run", "test"]
